version: '3.7'
services:
  bot_database:
    image: postgres
    container_name: bot_database
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    tty: true
    ports:
      - '35000:5432'
    env_file:
      - .env

  bot_api:
    container_name: bot_api
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app
    restart: always
    env_file:
      - .env
    depends_on:
      - bot_database
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DB_HOST=bot_database
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: npm run start

  migration:
    build:
      context: .
    restart: on-failure
    command:
      [
        './wait-for-it/wait-for-it.sh',
        'bot_database:5432',
        '--',
        'npm',
        'run',
        'migrate',
      ]
    links:
      - bot_database
    depends_on:
      - bot_database
    env_file: .env
    environment:
      - DB_HOST=bot_database

volumes:
  pg_data: null
